<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20151115155459 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE acme_blog_domain_model_post DROP FOREIGN KEY FK_EF2000AAC0155143");
		$this->addSql("CREATE TABLE maxs_blog_domain_model_blog (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(80) NOT NULL, description VARCHAR(150) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("DROP TABLE acme_blog_domain_model_blog");
		$this->addSql("DROP TABLE acme_blog_domain_model_post");
		$this->addSql("ALTER TABLE maxs_blog_domain_model_post ADD blog VARCHAR(40) DEFAULT NULL, ADD date DATETIME NOT NULL, ADD author VARCHAR(255) NOT NULL, ADD content LONGTEXT NOT NULL, CHANGE name title VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE maxs_blog_domain_model_post ADD CONSTRAINT FK_90DE26FCC0155143 FOREIGN KEY (blog) REFERENCES maxs_blog_domain_model_blog (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_90DE26FCC0155143 ON maxs_blog_domain_model_post (blog)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE maxs_blog_domain_model_post DROP FOREIGN KEY FK_90DE26FCC0155143");
		$this->addSql("CREATE TABLE acme_blog_domain_model_blog (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, title VARCHAR(80) NOT NULL COLLATE utf8_unicode_ci, description VARCHAR(150) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE acme_blog_domain_model_post (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, blog VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, subject VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, date DATETIME NOT NULL, author VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, content LONGTEXT NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_EF2000AAC0155143 (blog), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE acme_blog_domain_model_post ADD CONSTRAINT FK_EF2000AAC0155143 FOREIGN KEY (blog) REFERENCES acme_blog_domain_model_blog (persistence_object_identifier)");
		$this->addSql("DROP TABLE maxs_blog_domain_model_blog");
		$this->addSql("DROP INDEX IDX_90DE26FCC0155143 ON maxs_blog_domain_model_post");
		$this->addSql("ALTER TABLE maxs_blog_domain_model_post ADD name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, DROP blog, DROP title, DROP date, DROP author, DROP content");
	}
}